import Header from '@/components/layout/Header'
import './globals.css'
import { NextUIThemeProvider } from '@/config/provider/NextUIThemeProvider'
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
  <html lang="en">
    <body>
      <NextUIThemeProvider>
        <Header />
        {children}
      </NextUIThemeProvider>
      <Toaster />
    </body>
  </html>
  )
}
